
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
  
log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: web
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/"

http:
  
  services:
    
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
      
    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090

    mon-app:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://mon-app:8000/
        sticky:
          cookie:
            name: mon-app-loadbalancer
            secure: true

    back-resto:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://back-resto:3000/
        sticky:
          cookie:
            name: back-resto-loadbalancer
            secure: true

    front-commercial:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://front-commercial:8000/
        sticky:
          cookie:
            name: front-commercial-loadbalancer
            secure: true

    comm:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://comm:8000/
        sticky:
          cookie:
            name: comm-loadbalancer
            secure: true

    dev-api:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://dev-api:8000/
        sticky:
          cookie:
            name: dev-loadbalancer
            secure: true

    dev-front:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://dev-front:8080/
        sticky:
          cookie:
            name: dev-front-loadbalancer
            secure: true
  
  routers:

    grafana:
      rule: "Host(`grafana.localhost`)"
      service: "grafana"
      middlewares: "traefik-auth"

    traefik-ui:
        rule: "Host(`traefik-ui.localhost`)"
        service: "api@internal"
        middlewares: "traefik-auth"

    prometheus:
      rule: "Host(`prom.localhost`)"
      service: "prometheus"
      middlewares: "traefik-auth"

    mon-app-api-router:
      rule: PathPrefix(`/app/`)
      middlewares:
        - strip-prefix-app@file
      service: mon-app

    front-commercial-api-router:
      rule: PathPrefix(`/fcommercial/`)
      middlewares:
        - strip-prefix-fcommercial@file
      service: front-commercial

    back-resto-api-router:
      rule: PathPrefix(`/resto/`)
      middlewares:
        - strip-prefix-resto@file
      service: back-resto

    comm-api-router:
      rule: PathPrefix(`/comm/`)
      middlewares:
        - strip-prefix-comm@file
      service: comm

    dev-api-router:
      rule: PathPrefix(`/devapi/`)
      middlewares:
        - strip-prefix-dev-api@file
      service: dev-api

    dev-front-router:
      rule: PathPrefix(`/dev/`)
      middlewares:
        - strip-prefix-dev-front@file
      service: dev-front 
  
  middlewares:

    traefik-auth:
      basicauth:
        users: "admin:{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
        removeheader: true

    strip-prefix-comm:
      stripprefix:
        prefixes: /comm

    strip-prefix-app:
      stripprefix:
        prefixes: /app

    strip-prefix-resto:
      stripprefix:
        prefixes: /resto

    strip-prefix-fcommercial:
      stripprefix:
        prefixes: /fcommercial

    strip-prefix-dev-api:
      stripprefix:
        prefixes: /devapi

    strip-prefix-dev-front:
      stripprefix:
        prefixes: /dev