entryPoints:
  web:
    address: :80

  websecure:
    address: :443
  
log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/"

http:
  
  services:
    mon-app:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://mon-app:8000/
        sticky:
          cookie:
            name: mon-app-loadbalancer
            secure: true

    dev-api:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://dev-api:8000/
        sticky:
          cookie:
            name: dev-loadbalancer
            secure: true

    comm:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://comm:8000/
        sticky:
          cookie:
            name: comm-loadbalancer
            secure: true

    dev-front:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://dev-front:8080/
        sticky:
          cookie:
            name: dev-front-loadbalancer
            secure: true
  
  routers:
    mon-app-api-router:
      rule: PathPrefix(`/app/`)
      middlewares:
        - strip-prefix-app@file
      service: mon-app

    dev-api-router:
      rule: PathPrefix(`/devapi/`)
      middlewares:
        - strip-prefix-dev-api@file
      service: dev-api

    comm-api-router:
      rule: PathPrefix(`/comm/`)
      middlewares:
        - strip-prefix-comm@file
      service: comm 

    dev-front-router:
      rule: PathPrefix(`/dev/`)
      middlewares:
        - strip-prefix-dev-front@file
      service: dev-front 
  
  middlewares:
    strip-prefix-comm:
      stripprefix:
        prefixes: /comm

    strip-prefix-app:
      stripprefix:
        prefixes: /app

    strip-prefix-livreur:
      stripprefix: 
        prefixes: /livreur

    strip-prefix-dev-api:
      stripprefix: 
        prefixes: /devapi

    strip-prefix-dev-front:
      stripprefix: 
        prefixes: /dev
