entryPoints:
  web:
    address: :80

  websecure:
    address: :443

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: web
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/"

http:
  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090

    mon-app:
      loadBalancer:
        servers:
          - url: http://mon-app:8000/
        sticky:
          cookie:
            name: mon-app-loadbalancer
            secure: true

    back-resto:
      loadBalancer:
        servers:
          - url: http://back-resto:3000/
        sticky:
          cookie:
            name: back-resto-loadbalancer
            secure: true


    webs:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://webs:8002/
        sticky:
          cookie:
            name: webs-loadbalancer
            secure: true

    restaurateur:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://restaurateur:3002/
        sticky:
          cookie:
            name: restaurateur
            secure: true
    comm:
      loadBalancer:
        servers:
          - url: http://comm:8000/
        sticky:
          cookie:
            name: comm-loadbalancer
            secure: true

    back-livreur:
      loadBalancer:
        servers:
          - url: http://back-livreur:3005/
        sticky:
          cookie:
            name: back-livreur-loadbalancer
            secure: true

    dev-api:
      loadBalancer:
        servers:
          - url: http://dev-api:8000/
        sticky:
          cookie:
            name: dev-loadbalancer
            secure: true

    dev-front:
      loadBalancer:
        servers:
          - url: http://dev-front:8080/
        sticky:
          cookie:
            name: dev-front-loadbalancer
            secure: true

    front-commercial:
      loadBalancer:
        servers:
          - url: http://front-commercial:8000/
        sticky:
          cookie:
            name: front-commercial-loadbalancer
            secure: true

    front-client:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://front-client:3000/
        sticky:
          cookie:
            name: front-client-loadbalancer
            secure: true
  routers:
    grafana:
      rule: "Host(`grafana.localhost`)"
      service: grafana
      middlewares: traefik-auth

    traefik-ui:
      rule: "Host(`traefik-ui.localhost`)"
      service: api@internal
      middlewares: traefik-auth

    prometheus:
      rule: "Host(`prom.localhost`)"
      service: prometheus
      middlewares: traefik-auth

    mon-app-api-router:
      rule: PathPrefix(`/app/`)
      middlewares:
        - strip-prefix-app@file
      service: mon-app

    webs-api-router:
      rule: PathPrefix(`/webs/`)
      middlewares:
        - strip-prefix-webs@file
      service: webs
    back-resto-api-router:
      rule: PathPrefix(`/resto/`)
      middlewares:
        - strip-prefix-resto@file
      service: back-resto

    comm-api-router:
      rule: PathPrefix(`/comm/`)
      middlewares:
        - strip-prefix-comm@file
      service: comm

    dev-api-router:
      rule: PathPrefix(`/devapi/`)
      middlewares:
        - strip-prefix-dev-api@file
      service: dev-api

    dev-front-router:
      rule: PathPrefix(`/dev/`)
      middlewares:
        - strip-prefix-dev-front@file
      service: dev-front

    front-commercial-api-router:
      rule: PathPrefix(`/fcommercial/`)
      middlewares:
        - strip-prefix-fcommercial@file
      service: front-commercial

    front-client-api-router:
      rule: PathPrefix(`/frontclient/`)
      middlewares:
        - strip-prefix-frontclient@file
      service: front-client 
    restaurateur-api-router:
      rule: PathPrefix(`/restaurateur/`)
      middlewares:
        - strip-prefix-restaurateur@file
      service: restaurateur 
  middlewares:
    traefik-auth:
      basicauth:
        users: "admin:{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
        removeheader: true

    strip-prefix-comm:
      stripprefix:
        prefixes: /comm

    strip-prefix-back-livreur:
      stripprefix:
        prefixes: /back-livreur

    strip-prefix-webs:
      stripprefix:
        prefixes: /webs
    strip-prefix-frontclient:
      stripprefix:
        prefixes: /frontclient
    strip-prefix-restaurateur:
      stripprefix:
        prefixes: /restaurateur
    strip-prefix-app:
      stripprefix:
        prefixes: /app

    strip-prefix-resto:
      stripprefix:
        prefixes: /resto
    strip-prefix-dev-api:
      stripprefix:
        prefixes: /devapi

    strip-prefix-dev-front:
      stripprefix:
        prefixes: /dev

    strip-prefix-fcommercial:
      stripprefix:
        prefixes: /fcommercial