entryPoints:
  web:
    address: :80

  websecure:
    address: :443
  
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/"
http:
  services:
    mon-app:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://mon-app:8000/
        sticky:
          cookie:
            name: mon-app-loadbalancer
            secure: true
    back-resto:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://back-resto:3000/
        sticky:
          cookie:
            name: back-resto-loadbalancer
            secure: true

    webs:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://webs:8002/
        sticky:
          cookie:
            name: webs-loadbalancer
            secure: true

    restaurateur:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://restaurateur:3002/
        sticky:
          cookie:
            name: restaurateur
            secure: true
    comm:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://comm:8000/
        sticky:
          cookie:
            name: comm-loadbalancer
            secure: true
    front-client:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://front-client:3000/
        sticky:
          cookie:
            name: front-client-loadbalancer
            secure: true
  routers:
    mon-app-api-router:
      rule: PathPrefix(`/app/`)
      middlewares:
        - strip-prefix-app@file
      service: mon-app
    webs-api-router:
      rule: PathPrefix(`/webs/`)
      middlewares:
        - strip-prefix-webs@file
      service: webs
    back-resto-api-router:
      rule: PathPrefix(`/resto/`)
      middlewares:
        - strip-prefix-resto@file
      service: back-resto
    comm-api-router:
      rule: PathPrefix(`/comm/`)
      middlewares:
        - strip-prefix-comm@file
      service: comm 
    front-client-api-router:
      rule: PathPrefix(`/frontclient/`)
      middlewares:
        - strip-prefix-frontclient@file
      service: front-client 
    restaurateur-api-router:
      rule: PathPrefix(`/restaurateur/`)
      middlewares:
        - strip-prefix-restaurateur@file
      service: restaurateur 
  middlewares:
    strip-prefix-comm:
      stripprefix:
        prefixes: /comm
    strip-prefix-webs:
      stripprefix:
        prefixes: /webs
    strip-prefix-frontclient:
      stripprefix:
        prefixes: /frontclient
    strip-prefix-restaurateur:
      stripprefix:
        prefixes: /restaurateur
    strip-prefix-app:
      stripprefix:
        prefixes: /app
    strip-prefix-resto:
      stripprefix:
        prefixes: /resto
        