entryPoints:
  web:
    address: :80

  websecure:
    address: :443
  
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/"
http:
  services:
    mon-app:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://mon-app:8000/
        sticky:
          cookie:
            name: mon-app-loadbalancer
            secure: true
    comm:
      loadBalancer:
        # healthCheck:
        #   path: /health
        #   port: 8000
        servers:
          - url: http://comm:8000/
        sticky:
          cookie:
            name: comm-loadbalancer
            secure: true
  routers:
    mon-app-api-router:
      rule: PathPrefix(`/app/`)
      middlewares:
        - strip-prefix-app@file
      service: mon-app
    comm-api-router:
      rule: PathPrefix(`/comm/`)
      middlewares:
        - strip-prefix-comm@file
      service: comm 
  middlewares:
    strip-prefix-comm:
      stripprefix:
        prefixes: /comm
    strip-prefix-app:
      stripprefix:
        prefixes: /app
        